# Generated by Django 4.1.1 on 2022-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('artista', models.CharField(max_length=60)),
                ('anioLanzamiento', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vhs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=30)),
                ('anioLanzamiento', models.IntegerField()),
                ('director', models.CharField(max_length=60)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('desarrolladora', models.CharField(max_length=60)),
                ('plataforma', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
