# Generated by Django 4.1.1 on 2022-09-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBuster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cds',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vhs',
            name='status',
        ),
        migrations.RemoveField(
            model_name='videojuegos',
            name='status',
        ),
    ]
