# Generated by Django 4.1.2 on 2022-10-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBuster', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhs',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vhs'),
        ),
    ]
