# Generated by Django 4.1.2 on 2022-10-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBuster', '0004_vhs_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhs',
            name='imagen',
            field=models.ImageField(null=True, upload_to='vhs'),
        ),
    ]
