# Generated by Django 4.1.2 on 2022-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBuster', '0005_alter_vhs_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhs',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vhs'),
        ),
    ]
