# Generated by Django 4.1.2 on 2022-10-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBuster', '0007_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
